/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Stickman;

import Stickman.model.GameEngine;
import Stickman.model.Model;
import Stickman.view.GameWindow;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application
{
    public static void main(String[] args)
    {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage)
    {
        GameEngine model = new Model("src/main/resources/default.json");
        GameWindow window = new GameWindow(model, 800);


        primaryStage.setTitle("Stickman!");
        primaryStage.setScene(window.getScene());
        primaryStage.show();

        window.run();


    }

}